// Package age provides a cipher.KeyProvider backed by age recipients.
// It is the first-class KeyProvider for sops age encryption.
//
// # Recipient shapes
//
// The provider passes recipient strings straight through
// sops/v3/age.MasterKeyFromRecipient, which accepts four shapes. All
// four are supported with no extra configuration:
//
//   - X25519: age1...
//     The default and most common case. Generated by `age-keygen`.
//   - Hybrid (Kyber): age1pq1...
//     Post-quantum hybrid. Encrypts to both an X25519 key and a Kyber
//     key in one recipient string.
//   - Plugin: age1...1... (the second '1' separator indicates a plugin
//     namespace). Routed through filippo.io/age/plugin. Examples
//     include age-plugin-yubikey (age1yubikey1...) and scrypt-based
//     identities. The plugin binary must be on PATH at encrypt time.
//   - SSH: ssh-ed25519 AAAA..., ssh-rsa AAAA...
//     Reuses an existing SSH public key. Decryption uses the matching
//     private key in ~/.ssh, including encrypted keys (a passphrase
//     prompt fires on first use).
//
// All four shapes can be mixed inside a single key group. Any one
// identity holding a corresponding private key decrypts.
//
// # Identity sources
//
// At decryption time, sops resolves the identity from the same env
// the sops binary uses:
//
//   - SOPS_AGE_KEY: the literal age private key
//   - SOPS_AGE_KEY_FILE: a path to a file holding one or more
//     identities, one per line
//   - SOPS_AGE_KEY_CMD: a command whose stdout produces identities
//   - SOPS_AGE_SSH_PRIVATE_KEY_FILE: a path to an SSH private key
//
// The provider itself does not read identity material. It only
// supplies public recipients used to wrap the per-file data key.
//
// # Quick start
//
//	import (
//	    "github.com/dcadolph/cipher"
//	    "github.com/dcadolph/cipher/age"
//	)
//
//	kp, err := age.NewProvider("age1qyqsz...")
//	if err != nil { /* ... */ }
//	enc := cipher.NewEncoder(kp)
package age

import (
	"context"
	"fmt"

	filippoage "filippo.io/age"
	"github.com/getsops/sops/v3"
	sopsage "github.com/getsops/sops/v3/age"
	"github.com/getsops/sops/v3/keys"

	"github.com/dcadolph/cipher"
	"github.com/dcadolph/cipher/internal/util"
)

// Provider is a cipher.KeyProvider that produces a single sops.KeyGroup
// populated with age master keys derived from public recipients.
type Provider struct {
	// Recipients holds the age recipient strings (e.g. "age1...") used
	// to wrap the per-file data key.
	Recipients []string
}

// NewProvider returns a cipher.KeyProvider for the given age recipients.
// All recipients populate a single key group, matching sops' typical
// age usage where any holder of a corresponding identity can decrypt.
// Empty/whitespace-only entries are dropped. Returns an error if no
// usable recipients remain.
func NewProvider(recipients ...string) (cipher.KeyProvider, error) {
	cleaned := util.TrimEmpty(recipients)
	if len(cleaned) == 0 {
		return nil, fmt.Errorf("cipher/age: at least one recipient required")
	}
	return &Provider{Recipients: cleaned}, nil
}

// MustNewProvider wraps NewProvider and panics on error. Mirrors
// regexp.MustCompile and template.Must from the standard library:
// use only at init-time or in tests where construction failure is a
// developer error.
func MustNewProvider(recipients ...string) cipher.KeyProvider {
	kp, err := NewProvider(recipients...)
	if err != nil {
		panic(err)
	}
	return kp
}

// Identity is a freshly generated age identity pair.
type Identity struct {
	// Recipient is the public recipient string (age1...). Safe to share.
	// Pass this to NewProvider.
	Recipient string
	// Secret is the private identity string (AGE-SECRET-KEY-1...).
	// Treat as a credential. Anyone holding it can decrypt every file
	// encrypted to Recipient. Store it in a secret manager or write it
	// to a file with 0600 permissions and set SOPS_AGE_KEY or
	// SOPS_AGE_KEY_FILE so the decoder can find it.
	Secret string
}

// GenerateIdentity creates a fresh age X25519 identity and returns
// both halves: the public recipient string and the private identity
// string. The private string is never derivable from the recipient.
// Store it before discarding the returned value.
func GenerateIdentity() (*Identity, error) {
	id, err := filippoage.GenerateX25519Identity()
	if err != nil {
		return nil, fmt.Errorf("cipher/age: generate identity: %w", err)
	}
	return &Identity{
		Recipient: id.Recipient().String(),
		Secret:    id.String(),
	}, nil
}

// MustGenerateIdentity wraps GenerateIdentity and panics on error.
func MustGenerateIdentity() *Identity {
	id, err := GenerateIdentity()
	if err != nil {
		panic(err)
	}
	return id
}

// KeyGroups returns a single key group with one age master key per
// recipient. Implements cipher.KeyProvider.
func (p *Provider) KeyGroups(_ context.Context) ([]sops.KeyGroup, error) {
	if p == nil || len(p.Recipients) == 0 {
		return nil, fmt.Errorf("cipher/age: no recipients configured")
	}
	group := make(sops.KeyGroup, 0, len(p.Recipients))
	for _, r := range p.Recipients {
		mk, err := sopsage.MasterKeyFromRecipient(r)
		if err != nil {
			return nil, fmt.Errorf("cipher/age: recipient %q: %w", r, err)
		}
		group = append(group, keys.MasterKey(mk))
	}
	return []sops.KeyGroup{group}, nil
}
